version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
